// automatically generated by the FlatBuffers compiler, do not modify
// ignore_for_file: unused_import, unused_field, unused_element, unused_local_variable, constant_identifier_names

library exemplo;

import 'dart:typed_data' show Uint8List;

import 'package:flat_buffers/flat_buffers.dart' as fb;

class Pessoa {
  Pessoa._(this._bc, this._bcOffset);
  factory Pessoa(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<Pessoa> reader = _PessoaReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  String? get nome =>
      const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 4);
  int get idade => const fb.Int32Reader().vTableGet(_bc, _bcOffset, 6, 0);

  @override
  String toString() {
    return 'Pessoa{nome: ${nome}, idade: ${idade}}';
  }
}

class _PessoaReader extends fb.TableReader<Pessoa> {
  const _PessoaReader();

  @override
  Pessoa createObject(fb.BufferContext bc, int offset) => Pessoa._(bc, offset);
}

class PessoaBuilder {
  PessoaBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(2);
  }

  int addNomeOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }

  int addIdade(int? idade) {
    fbBuilder.addInt32(1, idade);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class PessoaObjectBuilder extends fb.ObjectBuilder {
  final String? _nome;
  final int? _idade;

  PessoaObjectBuilder({
    String? nome,
    int? idade,
  })  : _nome = nome,
        _idade = idade;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? nomeOffset =
        _nome == null ? null : fbBuilder.writeString(_nome!);
    fbBuilder.startTable(2);
    fbBuilder.addOffset(0, nomeOffset);
    fbBuilder.addInt32(1, _idade);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
